SET IDENTITY_INSERT [dbo].[Institutions] ON
INSERT INTO [dbo].[Institutions] ([ID], [Name], [Descriptions], [Type], [City], [InstitutionType]) VALUES (1, N'Kendriya Vidhyalaya', N'XYZ', 1, 1, 2)
INSERT INTO [dbo].[Institutions] ([ID], [Name], [Descriptions], [Type], [City], [InstitutionType]) VALUES (2, N'Kasthurba Gandhi Balika Vidhyalaya', N'XYZ', 1, 2, 2)
INSERT INTO [dbo].[Institutions] ([ID], [Name], [Descriptions], [Type], [City], [InstitutionType]) VALUES (3, N'TSR School', N'XYZ', 1, 1, 2)
INSERT INTO [dbo].[Institutions] ([ID], [Name], [Descriptions], [Type], [City], [InstitutionType]) VALUES (4, N'TSR School', N'XYZ', 1, 2, 2)
INSERT INTO [dbo].[Institutions] ([ID], [Name], [Descriptions], [Type], [City], [InstitutionType]) VALUES (5, N'Teach for India', N'XYZ', 1, 5, 1)
INSERT INTO [dbo].[Institutions] ([ID], [Name], [Descriptions], [Type], [City], [InstitutionType]) VALUES (6, N'Make a Difference', N'XYZ', 1, 13, 1)
INSERT INTO [dbo].[Institutions] ([ID], [Name], [Descriptions], [Type], [City], [InstitutionType]) VALUES (7, N'Pratham', N'XYZ', 1, 10, 1)
INSERT INTO [dbo].[Institutions] ([ID], [Name], [Descriptions], [Type], [City], [InstitutionType]) VALUES (8, N'Jr. Govt. Polytechnic', N'XYZ', 2, 1, 2)
INSERT INTO [dbo].[Institutions] ([ID], [Name], [Descriptions], [Type], [City], [InstitutionType]) VALUES (9, N'Govt. Jr. College', N'XYZ', 2, 2, 2)
INSERT INTO [dbo].[Institutions] ([ID], [Name], [Descriptions], [Type], [City], [InstitutionType]) VALUES (10, N'Govt. Degree College for Women', N'XYZ', 3, 1, 2)
INSERT INTO [dbo].[Institutions] ([ID], [Name], [Descriptions], [Type], [City], [InstitutionType]) VALUES (11, N'Kakatiya Govt. College', N'XYZ', 3, 2, 2)
INSERT INTO [dbo].[Institutions] ([ID], [Name], [Descriptions], [Type], [City], [InstitutionType]) VALUES (12, N'Elphinstone College', N'XYZ', 3, 12, 1)
INSERT INTO [dbo].[Institutions] ([ID], [Name], [Descriptions], [Type], [City], [InstitutionType]) VALUES (13, N'Govt. Medical College', N'XYZ', 3, 7, 2)
INSERT INTO [dbo].[Institutions] ([ID], [Name], [Descriptions], [Type], [City], [InstitutionType]) VALUES (14, N'Govt. Law College', N'XYZ', 3, 8, 2)
INSERT INTO [dbo].[Institutions] ([ID], [Name], [Descriptions], [Type], [City], [InstitutionType]) VALUES (15, N'Vivekanandha College of Nursing ', N'XYZ', 3, 5, 1)
INSERT INTO [dbo].[Institutions] ([ID], [Name], [Descriptions], [Type], [City], [InstitutionType]) VALUES (16, N'Vidhya Sagar Women''s College', N'XYZ', 3, 6, 1)
INSERT INTO [dbo].[Institutions] ([ID], [Name], [Descriptions], [Type], [City], [InstitutionType]) VALUES (17, N'Hindu College', N'XYZ', 3, 4, 2)
INSERT INTO [dbo].[Institutions] ([ID], [Name], [Descriptions], [Type], [City], [InstitutionType]) VALUES (18, N'SRR and CVR Govt. Degree College', N'XYZ', 3, 3, 1)
INSERT INTO [dbo].[Institutions] ([ID], [Name], [Descriptions], [Type], [City], [InstitutionType]) VALUES (19, N'Nagarjuna College of Nursing', N'XYZ', 3, 3, 2)
INSERT INTO [dbo].[Institutions] ([ID], [Name], [Descriptions], [Type], [City], [InstitutionType]) VALUES (20, N'National Institute of Electronics and Information Technology', N'XYZ', 3, 13, 2)
INSERT INTO [dbo].[Institutions] ([ID], [Name], [Descriptions], [Type], [City], [InstitutionType]) VALUES (21, N'Gargi College', N'XYZ', 3, 13, 1)
INSERT INTO [dbo].[Institutions] ([ID], [Name], [Descriptions], [Type], [City], [InstitutionType]) VALUES (22, N'Osmania University College for Women', N'XYZ', 4, 1, 2)
INSERT INTO [dbo].[Institutions] ([ID], [Name], [Descriptions], [Type], [City], [InstitutionType]) VALUES (23, N'Kasthurba Gandhi PG College for Women', N'XYZ', 4, 1, 2)
INSERT INTO [dbo].[Institutions] ([ID], [Name], [Descriptions], [Type], [City], [InstitutionType]) VALUES (24, N'Kakathiya University PG College', N'XYZ', 4, 2, 2)
SET IDENTITY_INSERT [dbo].[Institutions] OFF
