SET IDENTITY_INSERT [dbo].[Institutions] ON
INSERT INTO [dbo].[Institutions] ([ID], [Name], [Descriptions], [Type], [City], [InstitutionType]) VALUES (1, N'Kendriya Vidhyalaya', N'The Kendriya Vidyalayas Sangathan (lit. "central schools") is a system of central government schools in India that are instituted under the aegis of the Ministry of Human Resource Development (MHRD). It comprises over 1,199 schools in India (as of 1 November 2018) and three abroad. It is one of world''s largest chains of schools.', 1, 1, 2)
INSERT INTO [dbo].[Institutions] ([ID], [Name], [Descriptions], [Type], [City], [InstitutionType]) VALUES (2, N'Kasthurba Gandhi Balika Vidhyalaya', N'The Kasturba Gandhi Balika Vidyalaya or KGBV is a residential girls’ secondary school run by Government of India for the weaker sections in India

', 1, 2, 2)
INSERT INTO [dbo].[Institutions] ([ID], [Name], [Descriptions], [Type], [City], [InstitutionType]) VALUES (3, N'TSR School - Hyderabad', N'TREI or the Telangana Residential Educational Institutions Society is an initiative of the Indian Government. It was first set up in the year 1972 and it has been growing strong and managing more and more residential schools with every passing year. The main aim of the Indian Government in setting up the TREI society was to make sure that this society oversees the establishment of various residential schools around the state and successfully manage their functioning to provide proper education to all the children who need it- mainly those children from economically strained background and those from rural areas, who have limited access to education.', 1, 1, 2)
INSERT INTO [dbo].[Institutions] ([ID], [Name], [Descriptions], [Type], [City], [InstitutionType]) VALUES (4, N'TSR School - Guntur', N'TREI or the Telangana Residential Educational Institutions Society is an initiative of the Indian Government. It was first set up in the year 1972 and it has been growing strong and managing more and more residential schools with every passing year. The main aim of the Indian Government in setting up the TREI society was to make sure that this society oversees the establishment of various residential schools around the state and successfully manage their functioning to provide proper education to all the children who need it- mainly those children from economically strained background and those from rural areas, who have limited access to education.', 1, 2, 2)
INSERT INTO [dbo].[Institutions] ([ID], [Name], [Descriptions], [Type], [City], [InstitutionType]) VALUES (5, N'Teach for India', N'Embedded in our constitution is a social
contract founded on the promise of
justice, liberty, equality and fraternity
for all Indian citizens. We believe that this
promise forms the bedrock of our nation’s
ideals and must first be delivered within
our classrooms; the place where every
Indian’s journey begins. We believe that
our classrooms must mirror the social
justice we hope to see across the country.
We believe that the purpose of education
is to fully unleash every child’s potential.
We believe that India will not only be more
free and just, but also more equitable and
more compassionate.', 1, 5, 1)
INSERT INTO [dbo].[Institutions] ([ID], [Name], [Descriptions], [Type], [City], [InstitutionType]) VALUES (6, N'Make a Difference', N'Make a Difference is a registered society under the Travancore Cochin Literary, Scientific and Charitable Societies Registration Act, 1955. We are a 12A registered society with section 80(G) status of income tax act and we are eligible to receive foreign funding via the Foreign Contribution (Regulation) Act. Our financial records are audited annually by G. Joseph & Associates.

MAD follows all financial regulations set forth for non-profits by the Government of India, and is audited annually.', 1, 13, 1)
INSERT INTO [dbo].[Institutions] ([ID], [Name], [Descriptions], [Type], [City], [InstitutionType]) VALUES (7, N'Pratham', N'Pratham is an innovative learning organization created to improve the quality of education in India. As one of the largest non-governmental organizations in the country, Pratham focuses on high-quality, low-cost, and replicable interventions to address gaps in the education system. Established in 1995 to provide education to children in the slums of Mumbai, Pratham has grown both in scope and geographical coverage.', 1, 10, 1)
INSERT INTO [dbo].[Institutions] ([ID], [Name], [Descriptions], [Type], [City], [InstitutionType]) VALUES (8, N'Q.Q. Govt. Polytechnic', N'Quli Qutub Shah Government Polytechnicwas established by GO Ms No. 255 on 10th July 1985. It was initially started with three branches namely DCE, DME and DECE with an intake of 40 each and was located in a private building at Jahanuma. It was subsequently shifted to another private building at Chandrayangutta. Later on 20th November 1992 it was shifted to its permanent building at Chandulal Baradari, Near Zoo Park, Old City, Hyderabad.       ', 2, 1, 2)
INSERT INTO [dbo].[Institutions] ([ID], [Name], [Descriptions], [Type], [City], [InstitutionType]) VALUES (9, N'Govt. Jr. College for girls', N'The junior college GOVT. JR.COLLEGE FOR GIRLS , KRISHNA COLONY is located in the area WARANGAL of WARANGAL. GOVT. JR.COLLEGE FOR GIRLS , KRISHNA COLONY is in the WARANGAL district of ANDHRA PRADESH state. pincode is 506002. GOVT. JR.COLLEGE FOR GIRLS , KRISHNA COLONY WARANGAL was establised in the year 1970. The management of GOVT. JR.COLLEGE FOR GIRLS , KRISHNA COLONY is Department Of Education.

GOVT. JR.COLLEGE FOR GIRLS , KRISHNA COLONY is a Intermediate/Junior College school. The coeducation status of GOVT. JR.COLLEGE FOR GIRLS , KRISHNA COLONY is Girls. The medium of instruction in GOVT. JR.COLLEGE FOR GIRLS , KRISHNA COLONY .', 2, 2, 2)
INSERT INTO [dbo].[Institutions] ([ID], [Name], [Descriptions], [Type], [City], [InstitutionType]) VALUES (10, N'Indira Priyadarshini Govt. Degree College', N'Indira Priyadarshini Govt. Degree College for Women, Nampally,Hyderabad  a sterling landmark of Higher Education in the district of Hyderabad is established in the year 1981  with the prime motive of ensuring quality education within the reach of poor and down trodden urban students hailing from all the corners of the district.', 3, 1, 2)
INSERT INTO [dbo].[Institutions] ([ID], [Name], [Descriptions], [Type], [City], [InstitutionType]) VALUES (11, N'Kakatiya Govt. College', N'This college has started in 1972 as Government College for Men and after merging with Science sections of Kakatiya Medical College in 1978, this college was formed as Kakatiya Government College. In 2005 the college was accredited B++. In July 2012, during the first cycle of reaccreditation by NAAC, Bangalore it received A Grade with GPA Score 3.10. From a tiny institution in 1972 it has risen to the status of “lead college” of Warangal District, it stood 3rd among “A” Grade institutions of Andhra Pradesh and figures among 10% of “A” Grade Colleges of our country. This college has started in 1972 as Government College for Men and after merging with Science sections of Kakatiya Medical College in 1978, this college was formed as Kakatiya Government College. In 2005 the college was accredited B++. In July 2012, during the first cycle of reaccreditation by NAAC, Bangalore it received A Grade with GPA Score 3.10. From a tiny institution in 1972 it has risen to the status of “lead college” of Warangal District, it stood 3rd among “A” Grade institutions of Andhra Pradesh and figures among 10% of “A” Grade Colleges of our country.', 3, 2, 2)
INSERT INTO [dbo].[Institutions] ([ID], [Name], [Descriptions], [Type], [City], [InstitutionType]) VALUES (12, N'Elphinstone College', N'It''s a matter of great privilege for me to share my thoughts and feelings with you. Our college has History of more than 150 years. It has produced national leaders and played very important role in the building of Nation. Today we are in the 21st century and we have to face new challenges so I appeal to my students to make maximum use of college to come up with flying colours. 
', 3, 12, 1)
INSERT INTO [dbo].[Institutions] ([ID], [Name], [Descriptions], [Type], [City], [InstitutionType]) VALUES (13, N'Govt. Medical College', N'The Government Medical College, Thiruvananthapuram (also known as Thiruvananthapuram Medical College) is in Thiruvananthapuram (the capital of Kerala), India. Founded in 1951, it was dedicated by Prime Minister Jawaharlal Nehru and is Kerala''s oldest medical college. The college was known in early records as Medical College (of Thiruvananthapuram), since it was the only medical institute in the state at its inception.', 3, 7, 2)
INSERT INTO [dbo].[Institutions] ([ID], [Name], [Descriptions], [Type], [City], [InstitutionType]) VALUES (14, N'Govt. Law College', N'Government Law College, Thrissur, also known as Thrissur Law College, is situated in Ayyanthole. It is the fourth Government law college in Kerala and is owned by the Government of Kerala and affiliated to University of Calicut.', 3, 8, 2)
INSERT INTO [dbo].[Institutions] ([ID], [Name], [Descriptions], [Type], [City], [InstitutionType]) VALUES (15, N'Vivekanandha College of Nursing ', N'Vivekanandha College of Nursing was started in the year 1993. The College is recognized by the Government of Tamil Nadu, State Nursing council, approved by the Indian Nursing Council, New Delhi and affiliated to The Tamil Nadu Dr.M.G.R. Medical University, Chennai.Directorate of Medical Education,Chennai.', 3, 5, 1)
INSERT INTO [dbo].[Institutions] ([ID], [Name], [Descriptions], [Type], [City], [InstitutionType]) VALUES (16, N'Vidhya Sagar Women''s College', N'Vidhya Sagar Women’s College is named after Sri Iswar Chandra Vidhya Sagar, the great scholar, reformer who is ever cherished and remembered by people of our nation. Ours is the first women’s college incepted in the year 2005 in Chengalpet. Our College paves way for our students to face the challenges in the present educational scenario. Education, Empowerment, and Enhancement is the motto of our college. Empowerment and Enhancement is given to rural and poor women through Education. The college has got sprawling scenic campus of around 20 acres, one to one computer facility, library to cater the needs of all the departments, convenient transport facilities, excellent arrangements for Industrial visits, well furnished class rooms, good infrastructure, playground set in scenic atmosphere, 24 hours security service by professional security guards, well equipped labs, highly qualified and dedicated faculty, nutritious food and comfortable hostel facilities, active placement cell, scholarships for deserving students and Vidhya Sagar Empowerment Center which also includes personality enrichment, Spoken English through Language Lab, Karate and Yoga training programmes. The excellent academic records of our students do not end with results. They get translated into fruitful career in several corporate. We have the pleasure to inform that the leading software companies namely Cognizant Technology Solutions, TCS, Royal winding Sundaram Finance, and Jeetah Pharmaceuticals have selected sizable numbers of students from our college and they are doing well in their life. The Empowerment centre takes all efforts to promote women’s empowerment and enhance the self- employment zeal. To tap the innate talents of its members the centre conducted various certificate courses and 872 members were benefited due to those courses.', 3, 6, 1)
INSERT INTO [dbo].[Institutions] ([ID], [Name], [Descriptions], [Type], [City], [InstitutionType]) VALUES (17, N'Hindu College', N'This educational institution started its activities in 1930. The current Hindu high school started then. later it started offering other courses also. It offers graduate and under-graduate courses.[1] It has a Pharma College campus and a P.G. college on the Amaravathi Road which are recognized by the Acharya Nagarjuna University, Guntur.', 3, 4, 2)
INSERT INTO [dbo].[Institutions] ([ID], [Name], [Descriptions], [Type], [City], [InstitutionType]) VALUES (18, N'SRR and CVR Govt. Degree College', N'The SRR & CVR Govt. Degree College is a premier Institute of the region. SRR & CVR was established in the year 1937 by Sri Raja Rangayya Apparao. SRR & CVR is functioning under the aegis by the Commissionerate of collegiate Education, Govt of Andhra Pradesh. The campus is located at Vijayawada approximately 6 km from bus stand, Railway Station. The city of Vijayawada is well connected by road ways, rail ways and air ways with various parts of the country.', 3, 3, 1)
INSERT INTO [dbo].[Institutions] ([ID], [Name], [Descriptions], [Type], [City], [InstitutionType]) VALUES (19, N'Nagarjuna College of Nursing', N'The city of Vijayawada has a population of 1.5 million. This is the cultural, educational and financial centre for coastal Andhra Pradesh, the agriculture heart land of Krishna & Godavari delta. Nagarjuna Hospital, owned by Nagarjuna Hospitals Ltd is a 140 beds speciality hospital located in spacious premises of 4.5 acres. The hospital has excellent infrastructure incorporating state of the art medical technology supported by a team of experienced consultants, medical officers and qualified nurses. This is a tertiary referral centre for medical gastroenterology, surgical gastroenterology, respiratory medicine, intensive care medicine, anaesthesiology, orthopaedic surgery, trauma care, nephrology, neurology, neuro surgery and plastic surgery. In addition medicine, surgery, paediatrics, obstetrics and gynaecology services are also available.', 3, 3, 2)
INSERT INTO [dbo].[Institutions] ([ID], [Name], [Descriptions], [Type], [City], [InstitutionType]) VALUES (21, N'Gargi College', N'Gargi College was established in 1967 and has currently been awarded Grade-''A'' by NAAC. It has on its rolls about 3864 students. It has progressed steadily to become one of the leading institutes of the University of Delhi. It is definitely the most sought after women’s College in south Delhi campus for Sciences. It is the only women’s college in south campus that offers education in four streams, viz Sciences, Commerce and Arts, and a teacher training programme in Elementary Education. Post graduate programmes are offered in English, Political Science and Chemistry. The College offers a choice of subjects in 10 disciplines. In 2004 UGC conferred on the College the title, College with Potential for Excellence and bestowed a special grant to undertake research and community service projects. In 2009 the Department of biotechnology, Ministry of Science & Technology, Government of India awarded the institution the Star College Grant and a grant for establishing a bioinformatics facility at Gargi.
Faculty: The College has over 185 members of the faculty and most of them hold doctorate degrees. Some are engaged in major research programmes funded by UGC and DST. Faculty members are guiding M.Sc. and Ph.D. students and we have national- and international- level research collaborations. Not only the faculty but our students, too, regularly publish research papers.', 3, 13, 1)
INSERT INTO [dbo].[Institutions] ([ID], [Name], [Descriptions], [Type], [City], [InstitutionType]) VALUES (22, N'Osmania University College for Women', N'University College for Women is a constituent women''s college of Osmania University, in Koti, Hyderabad, TS, India. Its chief engineer was Nawab Khan Bahadur Mirza Akbar Baig.', 4, 1, 2)
INSERT INTO [dbo].[Institutions] ([ID], [Name], [Descriptions], [Type], [City], [InstitutionType]) VALUES (23, N'Kasthurba Gandhi PG College for Women', N'Named after the illustrious lady who stood by Mahatma Gandhi in thought and deed, Kasturba Gandhi College for Women was established in 1973 by the Osmania Graduates’ Association under the patronage of the Exhibition Society. Since then, the college has come a long way adding block by block over the years in its sprawling campus, spread over 3.85 acres of land in centrally located Marredpally, Secunderabad. In 1998 the college celebrated its Silver Jubilee, marking the occasion by laying foundation for yet another building, the Silver Jubilee Block. Starting with a modest student strength of 175 in the year 1973, the college now has a strength of about 2,800 students(UG & PG) with 90 teaching faculty, 71 non-teaching faculty. The college imparts value-based education to women to meet the modern day challenges.', 4, 1, 2)
INSERT INTO [dbo].[Institutions] ([ID], [Name], [Descriptions], [Type], [City], [InstitutionType]) VALUES (24, N'Kakathiya University PG College', N'The college was established in 1990 and has achieved steady growth in terms of academic activities, courses offered and infrastructural facilities. At present, the college is offering PG programmes in the disciplines of Economics, English, Political Science, History, Commerce, Financial Accounting and two professional 

courses, i.e., MBA and MCA. The college has a spacious building housing a library with a collection of twelve thousand books and journals and two laboratories with 50 computers and with other sophisticated equipment. The entire college is covered by the campus network with round the clock INTERNET facility.', 4, 2, 2)
SET IDENTITY_INSERT [dbo].[Institutions] OFF
